# Generated by Django 5.2 on 2025-05-08 09:46

from django.db import migrations

def create_initial_content_pages(apps, schema_editor):
    ContentPage = apps.get_model('core', 'ContentPage')
    
    # Create Privacy Policy if it doesn't exist
    if not ContentPage.objects.filter(page_type='PRIVACY').exists():
        ContentPage.objects.create(
            page_type='PRIVACY',
            content="""
# Privacy Policy

## Introduction
Welcome to our Privacy Policy. This document explains how we collect, use, and protect your personal information.

## Information We Collect
- Personal information such as name, email address, and phone number
- Usage data such as course progress and login times
- Payment information when you make a purchase

## How We Use Your Information
- To provide and maintain our service
- To notify you about changes to our service
- To provide customer support
- To gather analysis or valuable information so that we can improve our service

## Data Security
We implement appropriate security measures to protect your personal information.

## Your Rights
You have the right to access, update, or delete your personal information.

## Changes to This Privacy Policy
We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.

## Contact Us
If you have any questions about this Privacy Policy, please contact us.
            """
        )
    
    # Create Terms & Conditions if it doesn't exist
    if not ContentPage.objects.filter(page_type='TERMS').exists():
        ContentPage.objects.create(
            page_type='TERMS',
            content="""
# Terms and Conditions

## Introduction
These Terms and Conditions govern your use of our service and website.

## Acceptance of Terms
By accessing or using our service, you agree to be bound by these Terms.

## User Accounts
- You are responsible for maintaining the security of your account
- You are responsible for all activities that occur under your account
- You must notify us immediately of any breach of security or unauthorized use of your account

## Course Content
- All content provided on our platform is for educational purposes only
- You may not reproduce, distribute, or create derivative works from our content
- We reserve the right to modify or discontinue any course without notice

## Payment Terms
- All fees are non-refundable unless stated otherwise
- We reserve the right to change our fees at any time

## Limitation of Liability
We will not be liable for any indirect, incidental, special, or consequential damages.

## Governing Law
These Terms shall be governed and construed in accordance with the laws of [Your Country].

## Changes to Terms
We reserve the right to modify or replace these Terms at any time.

## Contact Us
If you have any questions about these Terms, please contact us.
            """
        )

def delete_content_pages(apps, schema_editor):
    # This function is only needed if you want to make the migration reversible
    ContentPage = apps.get_model('core', 'ContentPage')
    ContentPage.objects.filter(page_type__in=['PRIVACY', 'TERMS']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contentpage_generalsettings'),
    ]

    operations = [
         migrations.RunPython(create_initial_content_pages, delete_content_pages),
    ]
