# Generated by Django 5.2 on 2025-05-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_create_initial_content_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='small_desc',
            field=models.CharField(default='description', max_length=255),
        ),
    ]
