# Generated by Django 5.2 on 2025-05-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_purchase_plan_alter_category_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text="User's profile picture", null=True, upload_to='profile_pictures/'),
        ),
    ]
