# Generated by Django 5.2 on 2025-05-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='plan',
        ),
        migrations.AddField(
            model_name='course',
            name='price_lifetime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='course',
            name='price_one_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='course',
            name='price_three_months',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='plan_type',
            field=models.CharField(choices=[('ONE_MONTH', 'One Month'), ('THREE_MONTHS', 'Three Months'), ('LIFETIME', 'Lifetime')], default='ONE_MONTH', max_length=20),
        ),
    ]
