# Generated by Django 5.2 on 2025-05-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_purchase_plan_course_price_lifetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('ONE_MONTH', 'One Month'), ('THREE_MONTHS', 'Three Months'), ('LIFETIME', 'Lifetime')], max_length=20, null=True),
        ),
    ]
