# Generated by Django 5.2 on 2025-06-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_purchase_plan_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-date_uploaded']},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-date_enrolled']},
        ),
        migrations.AlterModelOptions(
            name='paymentorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchase_date']},
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_featured'], name='core_course_is_feat_1feaec_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category'], name='core_course_categor_243cf8_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['date_uploaded'], name='core_course_date_up_a84ef9_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user', 'course', 'is_active'], name='core_enroll_user_id_22a238_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['expiry_date'], name='core_enroll_expiry__80705b_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['plan_type'], name='core_enroll_plan_ty_8a9cb7_idx'),
        ),
        migrations.AddIndex(
            model_name='fcmdevice',
            index=models.Index(fields=['user', 'active'], name='core_fcmdev_user_id_02913c_idx'),
        ),
        migrations.AddIndex(
            model_name='fcmdevice',
            index=models.Index(fields=['device_id'], name='core_fcmdev_device__6e3db7_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_seen'], name='core_notifi_user_id_3dbc33_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='core_notifi_created_d0c445_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcard',
            index=models.Index(fields=['user', 'is_default'], name='core_paymen_user_id_5b96a9_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['user', 'status'], name='core_paymen_user_id_24aecd_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['razorpay_order_id'], name='core_paymen_razorpa_8c1b8f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['created_at'], name='core_paymen_created_5e495c_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['user', 'payment_status'], name='core_purcha_user_id_44fba3_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['purchase_date'], name='core_purcha_purchas_602874_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['transaction_id'], name='core_purcha_transac_9eee6d_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'is_active'], name='core_usersu_user_id_568b1a_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['end_date'], name='core_usersu_end_dat_333ec9_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['user'], name='core_wishli_user_id_b5812e_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['course'], name='core_wishli_course__fe3c66_idx'),
        ),
    ]
