# Generated by Django 5.2 on 2025-06-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0012_alter_course_options_alter_enrollment_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='course',
            name='core_course_is_feat_1feaec_idx',
        ),
        migrations.AddField(
            model_name='coursecurriculum',
            name='generation_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coursecurriculum',
            name='last_generation_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursecurriculum',
            name='presigned_expires_at',
            field=models.DateTimeField(blank=True, help_text='When presigned URL expires', null=True),
        ),
        migrations.AddField(
            model_name='coursecurriculum',
            name='presigned_url',
            field=models.URLField(blank=True, help_text='Pre-generated presigned URL'),
        ),
        migrations.AddField(
            model_name='coursecurriculum',
            name='url_generation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed'), ('expired', 'Expired'), ('not_needed', 'Not Needed')], default='pending', help_text='Status of presigned URL generation', max_length=20),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', 'is_featured'], name='core_course_categor_38e234_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_featured', 'date_uploaded'], name='core_course_is_feat_d4e3c1_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', 'date_uploaded'], name='core_course_categor_e0ee83_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_featured', 'category'], name='core_course_is_feat_5168d7_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['date_uploaded', 'is_featured'], name='core_course_date_up_7f9ca8_idx'),
        ),
        migrations.AddIndex(
            model_name='coursecurriculum',
            index=models.Index(fields=['course', 'order'], name='core_course_course__aa79d2_idx'),
        ),
        migrations.AddIndex(
            model_name='coursecurriculum',
            index=models.Index(fields=['url_generation_status', 'presigned_expires_at'], name='core_course_url_gen_af5b20_idx'),
        ),
        migrations.AddIndex(
            model_name='coursecurriculum',
            index=models.Index(fields=['course', 'url_generation_status'], name='core_course_course__442114_idx'),
        ),
        migrations.AddIndex(
            model_name='coursecurriculum',
            index=models.Index(fields=['presigned_expires_at'], name='core_course_presign_d20e83_idx'),
        ),
        migrations.AddIndex(
            model_name='coursecurriculum',
            index=models.Index(fields=['generation_attempts', 'url_generation_status'], name='core_course_generat_a26fb3_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user', 'is_active'], name='core_enroll_user_id_d39b76_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user', 'date_enrolled'], name='core_enroll_user_id_0d4163_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course', 'is_active'], name='core_enroll_course__0f84a6_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['is_active', 'date_enrolled'], name='core_enroll_is_acti_8dfa31_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user', 'is_active', 'date_enrolled'], name='core_enroll_user_id_730892_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['is_active', 'expiry_date'], name='core_enroll_is_acti_0d3125_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='core_user_email_38052c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='core_user_is_acti_8c954f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_staff', 'is_superuser'], name='core_user_is_staf_05cedd_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_joined'], name='core_user_date_jo_a935f6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'date_joined'], name='core_user_is_acti_2353a5_idx'),
        ),
    ]
