# Generated by Django 5.2 on 2025-06-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_course_core_course_is_feat_1feaec_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecurriculum',
            name='presigned_url',
            field=models.URLField(blank=True, help_text='Pre-generated presigned URL', max_length=10000),
        ),
        migrations.AlterField(
            model_name='coursecurriculum',
            name='video_url',
            field=models.URLField(blank=True, max_length=10000, null=True),
        ),
    ]
