# Generated by Django 5.2 on 2025-06-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_coursecurriculum_presigned_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecurriculum',
            name='presigned_url',
            field=models.URLField(blank=True, help_text='Pre-generated presigned URL', max_length=1000),
        ),
        migrations.AlterField(
            model_name='coursecurriculum',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='coursecurriculum',
            name='video_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
