# Generated by Django 5.2 on 2025-06-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_coursecurriculum_presigned_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecurriculum',
            name='presigned_url',
            field=models.TextField(blank=True, help_text='Pre-generated presigned URL'),
        ),
        migrations.AlterField(
            model_name='coursecurriculum',
            name='video_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
