# Generated by Django 5.2 on 2025-08-20 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_coursecurriculum_presigned_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppleIAPProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(help_text='Apple Product ID (e.g., com.yourapp.course1_monthly)', max_length=100, unique=True)),
                ('plan_type', models.CharField(choices=[('ONE_MONTH', 'One Month'), ('THREE_MONTHS', 'Three Months'), ('LIFETIME', 'Lifetime')], max_length=20)),
                ('price_usd', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppleIAPReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_data', models.TextField(help_text='Base64 encoded receipt data')),
                ('verification_response', models.JSONField(default=dict, help_text="Apple's verification response")),
                ('verification_date', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('environment', models.CharField(choices=[('Production', 'Production'), ('Sandbox', 'Sandbox')], default='Production', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentLinkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('ONE_MONTH', 'One Month'), ('THREE_MONTHS', 'Three Months'), ('LIFETIME', 'Lifetime')], max_length=20)),
                ('payment_link_id', models.CharField(help_text='Unique identifier for the payment link', max_length=100, unique=True)),
                ('payment_link_url', models.URLField(blank=True, help_text='Generated payment link URL', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EMAIL_SENT', 'Email Sent'), ('PAYMENT_COMPLETED', 'Payment Completed'), ('ENROLLMENT_COMPLETED', 'Enrollment Completed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent_count', models.PositiveIntegerField(default=0)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('admin_contacted', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='Link expiration date')),
            ],
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='payment_method',
            field=models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('PAYMENT_LINK', 'Payment Link')], default='RAZORPAY', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('ONE_MONTH', 'One Month'), ('THREE_MONTHS', 'Three Months'), ('LIFETIME', 'Lifetime')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='apple_product_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='apple_receipt_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='apple_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='apple_verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_gateway',
            field=models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('APPLE_IAP', 'Apple In-App Purchase')], default='RAZORPAY', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('LINK_REQUESTED', 'Link Requested'), ('LINK_EXPIRED', 'Link Expired')], default='CREATED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['apple_transaction_id'], name='core_purcha_apple_t_bc02e4_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['payment_gateway'], name='core_purcha_payment_be3290_idx'),
        ),
        migrations.AddField(
            model_name='appleiapproduct',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apple_products', to='core.course'),
        ),
        migrations.AddField(
            model_name='appleiapreceipt',
            name='purchase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apple_receipt', to='core.purchase'),
        ),
        migrations.AddField(
            model_name='paymentlinkrequest',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_link_requests', to='core.course'),
        ),
        migrations.AddField(
            model_name='paymentlinkrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_link_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='appleiapproduct',
            index=models.Index(fields=['product_id', 'is_active'], name='core_applei_product_e83082_idx'),
        ),
        migrations.AddIndex(
            model_name='appleiapproduct',
            index=models.Index(fields=['course', 'plan_type'], name='core_applei_course__43b0fd_idx'),
        ),
        migrations.AddIndex(
            model_name='appleiapreceipt',
            index=models.Index(fields=['verification_date'], name='core_applei_verific_eb86d9_idx'),
        ),
        migrations.AddIndex(
            model_name='appleiapreceipt',
            index=models.Index(fields=['is_valid', 'environment'], name='core_applei_is_vali_ac4cb8_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentlinkrequest',
            index=models.Index(fields=['payment_link_id'], name='core_paymen_payment_95e868_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentlinkrequest',
            index=models.Index(fields=['status', 'created_at'], name='core_paymen_status_a5e2b0_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentlinkrequest',
            index=models.Index(fields=['user', 'status'], name='core_paymen_user_id_f471b0_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentlinkrequest',
            index=models.Index(fields=['expires_at'], name='core_paymen_expires_5ec78c_idx'),
        ),
    ]
